### ISSUE TITLE
large data sets

### ISSUE THREAD

**Issue by mmichelli** [hoodiehq/hoodie#139]
Can't store large data sets because it syncs to to the browser... or can you?

DOMException {message: "An attempt was made to add something to storage that exceeded the quota.", name: "QuotaExceededError", code: 22, stack: "Error: An attempt was made to add something to

**Comment by gr2m** [comment]
This is a known limitation, and we are  going to do two things about it:
1. Using IndexedDB instead of localStorage, probably [PouchDB](http://pouchdb.com/). That usually has more quota
2. Add support to sync only a subset of your data

We are currently focussing on other things like the plugin architecture, but will get back to this. 

How come you have so much data anyway? Could you elaborate your use case? That'd help a lot to make the right decisions once we get started to work in this.

You can also contribute 2. yourself, I'm happy to assist with that.

**Comment by mmichelli** [comment]
I'm making an app, that the user will be logging 20000 data points, they will be inspecting power line posts (300km) and each post has at least a GPS point and a yes/no. Thought hoodie would be good, has it's a short run project (alive for two weeks), it has to be ready by monday and has to work offline most of the time (on a iPad). But now I'm in trouble… 

Pouch looks good, how much work am I looking at here? 

Thanks for your help, 

Mario

**Comment by mmichelli** [comment]
Looking at it, I think I'll just use Pouch by itself for tomorrow and then look at a hoodie.js solution, I'm keen to work on the project.

Thanks, 
Mario

**Comment by gr2m** [comment]
That's great, would love to hear how things work.out! Dale is a good friend of ours

```
—
```

Gregor Martynus
