### ISSUE TITLE
High memory use

### ISSUE THREAD

**Issue by inator** [hoodiehq/hoodie#22]
I’m seeing a dramatic increase in memory use - where older Hoodie would consume < 200Mb while idle, New Hoodie consumes > 700Mb.

**Comment by janl** [comment]
Is this just starting and empty instance with no users?

**Comment by janl** [comment]
Which node version / OS, etc? which hoodie version exactly etc :D

**Comment by boennemann** [comment]
As discussed in the [chat](http://hood.ie/chat/) this is **very** likely due to the use of PouchDB server instead of CouchDB. As we recommend using a CouchDB for a production setup the "new" hoodie should have an equal or lower memory consumption.

@inator I'm closing for now, but please update us if the problem persists, or post the new memory consumption w/o PouchDB and we'll reopen as soon as we've verified that this is a problem affecting the production setup.

Best,
Stephan

**Comment by nolanlawson** [comment]
Yikes, I hope this is in reference to PouchDB Server and not PouchDB in the client? As for why PouchDB Server takes up so much more RAM than CouchDB, that's still kind of a mystery to me. Worth profiling!

**Comment by boennemann** [comment]
@nolanlawson Yes, this is just PouchDB _Server_.
