### ISSUE TITLE
Wrong Version number in dist.min file for tag 0.6.1

### ISSUE THREAD

**Issue by robinboehm** [hoodiehq/hoodie#231]
Looks like there was no new build between 0.6.0 and 0.6.1 tag

https://github.com/hoodiehq/hoodie.js/blob/master/dist/hoodie.min.js#L1

**Comment by svnlto** [comment]
@gr2m we need to refine publishing hoodie.js and the use of grunt bump, I think.

lint - tests - browserify - bump version numbers - concat - uglify - and then publish

is what it should be, as of now we only every get the previous versions in the concat tasks hence this issue.

**Comment by gr2m** [comment]
yes, the problem is that hoodie.js is build before the version number is bumped. So the code is correct, but the version number is not.

We us https://github.com/vojtajina/grunt-bump, there is also https://github.com/gruntjs/grunt-contrib-bump, but neither supports running a task between bumping the versions and committing/creating a tag. Needs some more research

**Comment by gr2m** [comment]
see https://github.com/vojtajina/grunt-bump/issues/47

**Comment by svnlto** [comment]
:+1:

**Comment by gr2m** [comment]
I think I found a fix for that, from the grunt-bump docs:

> Sometimes you want to run another task between bumping the version and commiting, for instance generate changelog. You can use bump-only and bump-commit to achieve that:

```
$ grunt bump-only:minor
$ grunt changelog
$ grunt bump-commit
```

I'll make single task out of it, that has the build task in between

**Comment by robinboehm** [comment]
:+1:
