### ISSUE TITLE
hoodie.account.signUp should sign out any existing session

### ISSUE THREAD

**Issue by caolan** [hoodiehq/hoodie#243]
Currently it gives you an error, but I don't really see why you'd want it to do anything other than sign-up and login as the new user.

**Comment by gr2m** [comment]
Hmm yeah, good point ... I think it's an edge case, but I can't think of why we shouldn't do as you suggest

**Comment by treasonx** [comment]
I think that throwing an error is more appropriate than silently ending the current user session. 

For example if I had a bug in my application code where I accidentally allow a user to enter the signup workflow while they are already logged in, it would be a huge help if the API failed fast! Otherwise I might end up with users creating new accounts without realizing it, and this would lead to a difficult bug to track down. If my application accidentally allowed the creation of multiple account, a user might end up with data spread across multiple accounts! Which could be difficult to fix once discovered.

If my application workflow should allow the creating of a new account while logged in I could easily catch the error and end the session in the application code. I would explicitly be making the decision to allow for a behavior which doesn't seem normal from the framework's standpoint.

I am a fan of a framework API failing fast instead of trying to do the "right thing" for me. Allowing the creation of a new account while logged in seems application specific.

**Comment by matthewhaworth** [comment]
I have to agree with treasonx, it's application logic and should fail if a session exists.

**Comment by gr2m** [comment]
no longer relevant with new Hoodie, as `hoodie.account.signUp()` does no longer sign in the user automatically, `hoodie.account.signIn()` has to be called separately
