### ISSUE TITLE
Introduce proper UUID's

### ISSUE THREAD

**Issue by svnlto** [hoodiehq/hoodie#257]
Replace custom Pseudo ID generation [1] with something decent / reliable [2].

[1] https://github.com/hoodiehq/hoodie.js/blob/master/src/utils/generate_id.js
[2] https://github.com/broofa/node-uuid

**Comment by gr2m** [comment]
I did some research back when I started to use current algorithm in minutes.io. The chance of conflict with the current algorithm is 1 : 80 Billion or so. Is that not decent enough? 

I don't mind going with something else, but the IDs should stay as concise as they are right now, meaning instead of `6790ac7c-24ac-4f98-8464-42f6d98a53ae` it should skip the `-` and also use `g-z`. You think that's possible?

As a side node, the UUIds should be valid for CouchDB database names to prevent problems. That means no uppercase letters.

**Comment by svnlto** [comment]
Just wanted to be more in line with `pouchdb` https://github.com/daleharvey/pouchdb/blob/master/lib/deps/uuid.js really.

**Comment by gr2m** [comment]
how about we use pouchdb's uuid, and do something like this for Hoodie-internal use?

``` js
var uuid = require('uuid')
// helper to generate unique ids.
function generateId (length) {
  return uuid(length).toLowerCase()
}

module.exports = generateId;
```

**Comment by svnlto** [comment]
perfect.
