### ISSUE TITLE
Add Hoodie.toString()

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#260]
It'd be nice to type in `Hoodie` in the web developer console and get something like `Hoodie Version 0.7.2, rev b093127`, we could even list installed plugins, evtl. NodeJs/CouchDB version etc, if we'd add this information dynamically when served via /_api/_files/hoodie.js

Just a thought, this is a nice-to-have

**Comment by adamyeats-zz** [comment]
@gr2m @svnlto How come this issue was closed? This seems like a good idea. `Hoodie.toString()` doesn't seem semantically correct though, so I propose maybe exposing a `.VERSION` string a and `.installedPlugins` computed property. I imagine the latter could work like so:

```
  Object.defineProperty(Hoodie, 'installedPlugins', {
    get: function () {
      return [logic for getting list of installed plugins here]
    }
  });
```

Not sure what browser support is like for `Object.defineProperty()` though.

**Comment by gr2m** [comment]
It's in backlog, we'll get back to it—
Gregor Martynus

**Comment by adamyeats-zz** [comment]
@gr2m I can send a PR for this if you'd prefer. :)

**Comment by gr2m** [comment]
We first need yo get the versions into Hoodie as part of the build process. The toString() method does automatically get run when you just enter hoodie in the console, that's why I suggested it—
Gregor Martynus

**Comment by adamyeats-zz** [comment]
:+1:
