### ISSUE TITLE
Update browserify, grunt-browserify etc.

### ISSUE THREAD

**Issue by boennemann** [hoodiehq/hoodie#337]
```
$ npm update grunt-browserify
npm ERR! peerinvalid The package browserify does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-browserify@1.2.12 wants browserify@>=2.35 < 3.0.0
npm ERR! peerinvalid Peer karma-browserify@0.2.1 wants browserify@>=3.30.5
```

**Comment by gr2m** [comment]
it's kind of done in https://github.com/hoodiehq/hoodie.js/tree/karma_browserify_update, but problem is that for some strange reason, the tests do not run any more, at least not all at once when running with phantomJS in single-run mode. It looks pretty random :/ 

We have it merged into https://github.com/hoodiehq/hoodie.js/tree/promise_restored, and will try to get it fixed in there, so this should be fixed when the new promise implementation gets merged.

**Comment by svnlto** [comment]
I've updated karma dependencies on the promise_restored branch already. so whenever we are done with promises we can merge this too, unless you'd want to cherry pick those commits.
