### ISSUE TITLE
Data Synchronization Priority

### ISSUE THREAD

**Issue by allain** [hoodiehq/hoodie#344]
As a user's data grows, the amount of synchronization needed to get a user up and running on a new machine grows too (obviously). The order of synchronization is not controllable as far as I can tell, so it's possible that all of the data needed to render a consistent first screen is not available until all of the synchronization has completed.

As a real case, say I have 1000 large, tagged, records to synchronize and the tags are loaded last, I can delay the display of those records, or delay the display of their tags. Neither approach is obvious for a naive user. 

I can think of solutions but they all require me to step outside of the noBackend feel of hoodie. Best would be to be able to define a priority field on the records and then somehow limit replication to progressively more permissive ranges of priorities until it's replicating normally.

If possible, this approach would allow me to order tags to be loaded before their associated records or even to store naive snapshots of the data that I know I'll need to render it on first load (ugly, but workable).

Thoughts?

**Comment by gr2m** [comment]
If I understand you correctly, selective sync is what you want. We have an issue for it: https://github.com/hoodiehq/hoodie.js/issues/152. I'll add your input to that issue. I'd also reach out to you once we start working on it, if that's ok?

The basic idea at the moment is:
1. Make the bootstrap request customizable. It could be a CouchDB view instead of call to `_changes`
2. Add an `archivedAt` property (or similar). All docs with that property will not be synced automatically to the frontend, they have to be requested when needed.
