### ISSUE TITLE
Document update conflicts when replicating _users

### ISSUE THREAD

**Issue by varunnaik** [hoodiehq/hoodie#374]
As part of the application I am working on, we set up a replication between multiple CouchDbs. Our goal is to replicate users between machines so a user account created on one machine works seamlessly on another machine. To do this, we replicate the _users database between machines.

In practice, after replication, what is observed is that login fails with an error, 'Document update conflicts must be resolved before this document can be used for authentication purposes.' - this seems to happen randomly, and there should be no conflict because the user was created on one machine and doesn't exist on the other machines at all.

This does seem to be a CouchDb problem, but any help would be appreciated.

cc @janl @gr2m @peetersn

**Comment by janl** [comment]
is anything else creating users on the couchdb node?

CouchDB doesn’t introduce conflict will-nilly, so I’m fairly confident that this is an outside error.

As a stop-gap, you could just resolve all conflicts after the replication of the users db.

**Comment by varunnaik** [comment]
Nope, nothing except Hoodie. We do have star replications set up between all our nodes, (every node replicates _users to every other node) - could that be a problem?

Sometimes I see this error when creating a new user, i.e., I use hoodie.account.signUp() to create a user and that call returns an error saying there's been a document update conflict.

> As a stop-gap, you could just resolve all conflicts after the replication of the users db.

Could you elaborate a bit on this please? How can I do this automatically?

**Comment by janl** [comment]
ah yes, since hoodie plugins will alter the user docs you can get inconstancies if you have it going over a star. Are you running hoodie backends behind all connected CouchDBs? (that doesn’t really work yet, as we’ve explained elsewhere :)

> Could you elaborate a bit on this please? How can I do this automatically?

get the _changes?include_docs=true feed and look for a _conflicts member in the docs.

**Comment by varunnaik** [comment]
Yes, we are using hoodie backends behind all connected CouchDBs. What would break, everything?

> get the _changes?include_docs=true feed and look for a _conflicts member in the docs.

I could do that. But how would I trigger the script that resolves conflicts? Is there any way of knowing when a replication has finished in Hoodieland or in node? And the script that resolves conflicts would get all docs that have conflicts using the URL you mentioned, delete all conflicting revisions and delete the _conflicts member and save the doc again, is that right?

**Comment by janl** [comment]
> Yes, we are using hoodie backends behind all connected CouchDBs. What would break, everything?

Assuming you also replicate all user databases and everything.

In short: we don’t know. Possibly everything. For example a task that sends an email (I know you are not sending emails, but bear with me for an example that should result in only one external action = one email sent): if you have two Hoodie instances running behind two CouchDB instances that replicate, and one client creates a new task to send an email, that task gets replicated to all Hoodie backends and each backend will try to send the email, resulting in two emails sent in the end.

There might be more things like that. Hoodie will eventually support this, and the design allows for it, but the current implementation doesn’t do this and it is currently not on the roadmap to get this supported. Sorry!

**Comment by janl** [comment]
> I could do that. But how would I trigger the script that resolves conflicts? Is there any way of knowing when a replication has finished in Hoodieland or in node? And the script that resolves conflicts would get all docs that have conflicts using the URL you mentioned, delete all conflicting revisions and delete the _conflicts member and save the doc again, is that right?

Start the script when you start Hoodie (could even be a Hoodie plugin) and keep listening to _changes continuously.

**Comment by varunnaik** [comment]
I think I've understood what's happening now.
That was very detailed and useful, thank you for the help :-)

**Comment by janl** [comment]
Cool, glad I could help. Closing this now, but feel free to reopen if there is more :)

**Comment by peetersn** [comment]
@janl Sorry to comment on this closed issue, but this is quite fundamental for us. This is pretty much a deal breaker for our architecture (and our usage of Hoodie). 

While I understand that running in a cluster will introduce idempotency issues (like the email example that you mentioned), I'm confused why the replication of standard "users" document is giving problems, this should be pretty standard. Also why are _users documents modified and lead to conflicts is quite unexpected (considering that this is not something entirely Hoodie-specific). The users is the only place where we're seeing issues, the rest works fine. 

Maybe a naive suggestion, but documents in the `_users` DB have no timestamps, let's imagine they would have, then they would replicate without conflicts, wouldn't they?

Also, when conflicts occur, Hoodie seems to not behave well. Is that something that you've experienced?

**Comment by gr2m** [comment]
Just fyi Jan will be mostly offline as he focuses on JSConfEU now, might take until some time next week until he can respond. I'll ping him on it when he's back

**Comment by janl** [comment]
@peetersn no worries about commenting on this issue.

I understand that this is a problem or your setup, but we’ve been very open in the past that this is not specifically a supported configuration.

The scenario is as follows:

hoodie.js (frontend) creates a document in the `/_users` database. Then hoodie-plugin-users, listening to `/_users/_changes` reacts on the new doc coming in and sets up the user’s database and then confirms the user by updating the user doc’s `confirmed` property to `true`. Both hoodie.js and hoodie-plugin-users also update the `updatedAt` property with the current timestamp of user sign up and confirmation respectively.

If you now get replication, which also listens on `/_users/_changes` gets in and replicates the user doc _before_ hoodie-plugin-users gets to confirm it, then the same dance as above will happen on the target CouchDB, with replication eventually creating a conflict, because most likely the timestamps will differ.

I guess, while writing this up now, you could do filtered replication, instead of replication, and not allow unconfirmed user docs to be replicated, thus confining the actions of the users plugin to the CouchDB instance that the user was connected to when signing up. But then you will have to take over other duties like creating the user’s database on the target CouchDB as well, but I assume you already have some infrastructure to make that happen outside of Hoodie (and if not, with /_db_updates, this should be reasonably easy to build).

Hope this helps!

As Gregor writes, from now on, I’ll be “offline” until Monday.

**Comment by gr2m** [comment]
can we close this, or create an actionable follow up issue?
