### ISSUE TITLE
putAttachments

### ISSUE THREAD

**Issue by mmichelli** [hoodiehq/hoodie#403]
I would like a write a plugin to handle attachments, how would I directly connect to the new plugin? 

I would like to make something like this:
db.putAttachment(docId, attachmentId, rev, attachment, type, [callback]);

https://wiki.apache.org/couchdb/HTTP_Document_API#Attachments

**Comment by gr2m** [comment]
Hey @mmichelli,

having a solid plugin for uploads would be great indeed, it's a recurring request from the community. We built Hoodie apps with uploads in the past, but it was too app-specific. 

I see two ways you could approach it.
1. Store attachments in the `_attachments` property – that will work out of the box. But note that Hoodie currently uses localStorage as its persistent layer, which is limited in size. But we are [migrating to Pouch](https://github.com/hoodiehq/wip-hoodie-store-on-pouchdb), which has better binary handling
2. Another alternative would be to use a 3rd party service like https://transloadit.com/. Writing a plugin that integrates with such a service should be pretty straight forward.

Go with `1.` if you need "offline uploads", meaning that you need to be able to upload files while you are offline, waiting for a connection for them to be synchronized. Otherwise, go with `2.`. 

Storing binary files locally in JavaScript is still a huge mess and very hard to handle properly, I'd recommend to go with `2.` if you can.

**Comment by zoepage** [comment]
@mmichelli did @gr2m answer help? :)

**Comment by mmichelli** [comment]
Hi, 

Yes, sorry for the delay, this is helpful. I prefer of the second approach. I was thinking that an appcache file would help for offline situations. 

Can a backend plugin have a web-service interface, could it save the image onto the server and then store the url or pass it back at least. Why a third party service?

**Comment by gr2m** [comment]
Plugins can expose own REST APIs which which you can do what ever you like, so instead of using a third party application, you could implement such a functionality yourself and expose respective APIs your self.

Let me know if you have any farther questions

**Comment by mmichelli** [comment]
I created a plugin that saves the file, as you suggested.

**Comment by mmichelli** [comment]
thanks

**Comment by zoepage** [comment]
@mmichelli if you open source it, could you add a link to the module? :)

**Comment by mmichelli** [comment]
I will do, just have to get around to it.
