### ISSUE TITLE
Q: Is there a difference in the way you include hoodie.js?

### ISSUE THREAD

**Issue by idanb11** [hoodiehq/hoodie#404]
HI all, 
Great great framework.... :100: 

One question:
Is there a difference in the way you include hoodie.js:
`<script src="/_api/_files/hoodie.js"></script>`
`<script src="./bower_components/hoodie/dist/hoodie.min.js"></script>`

**Comment by gr2m** [comment]
Hey @idanb11, glad you like Hoodie :)

The right way to include Hoodie is 
`<script src="/_api/_files/hoodie.js"></script>`

We'll remove the bower support soon.

The reason is that `/_api/_files/hoodie.js` bundles all frontend JavaScript code, not only from hoodie.js-core, but also from your app's plugins.
