### ISSUE TITLE
how to persist state not-yet-saved before signout?

### ISSUE THREAD

**Issue by davidascher** [hoodiehq/hoodie#46]
STRs:
- sign in to demo app
- quickly type in a bunch of new tasks (10 or so)
- quickly sign out.
- sign in again

the set of tasks that will have been saved can be a subset of the set of tasks entered.  Somehow, the app needs to "persist to disk" before signing out.  Filing here rather than in demo app as I expect there's a bigger architectural discussion to have about how to make that happen.

**Comment by gr2m** [comment]
Hey @davidascher, it's an interesting idea, I thought about that myself a few months back, but didn't come up with any good solution. The only approach I could come up with would be using the FileWriter API, which is only supported by Chrome so far (http://caniuse.com/filesystem)

But regarding your usecase, I think the problem is that there is a 2s timeout, before data is pushed to remote. If you sign before that 2s or while the push request is pending, you might loose data.

You can use `hoodie.remote.push()` to manually trigger a sync from local to remote.
You could try something like this:

```
objects = [
  { title: "Do this" },
  { title: "Do that" },
]
handleError = function( error ) { alert("something went wrong:\n" +JSON.stringify(error, '', '  ')}

hoodie.account.signIn("user, "pass")
.then( objects.map( function(o) { return hoodie.store.add("task", o.title) } ) )
.then( hoodie.remote.push )
.then( hoodie.account.signOut )
.fail( handleError )
```

**Comment by gr2m** [comment]
In general, I'd recommend to check if there are any local changes before a user signes out. You can check that with `hoodie.store.isDirty()`
