### ISSUE TITLE
findAll inside signIn callback doesn't return any results

### ISSUE THREAD

**Issue by max-mapper** [hoodiehq/hoodie#49]
hiya, this code doesn't return any documents:

``` js
hoodie.account.on('signin', function() {
  hoodie.store.findAll('email').done(function (objects) { console.log(objects) })
})
hoodie.account.signIn('test', 'test')
```

but if I wait a second and then run `hoodie.store.findAll('email').done(function (objects) { console.log(objects) })` again then all the documents show up

**Comment by gr2m** [comment]
yeah, that's something we are aware of, and I'm sure we opened a ticket for it, just can't find it atm ;-)

So reason is, that `store.findAll()`, like all the other store methods do currently only check for data in the local browser store. After signIn, there's nothing, it first needs to bootstrap.

But we gonna change that, so that in a state of `bootstrapping`, hoodie will be waiting for bootstrapping to finish before doing its find thing. I'll keep you posted.

Until then, you could do something like

``` js
hoodie.account.signIn('test', 'test').then( function() {
  hoodie.store.findAll('email').done(function (objects) { console.log(objects) })
})
```
