### ISSUE TITLE
Bug: Displayed host in command line instructions is not accessible

### ISSUE THREAD

**Issue by machikoyasuda** [hoodiehq/hoodie#541]
After I first installed and ran `npm start`, the command line instructions says to go to `http://Machikos-MacBook-Pro.local:8080` instead of `http://localhost:8080/`

```
➜   hoodie-app-mapchat git:(master) ✗ npm start
> hoodie-app-mapchat@1.0.2 start /Users/machikoyasuda/practice/hoodie-app-mapchat
> hoodie
🐶  Your Hoodie app has started on: http://Machikos-MacBook-Pro.local:8080
Stop server with control + c
```

<img width="631" alt="screenshot 2016-07-27 19 56 37" src="https://cloud.githubusercontent.com/assets/3673236/17199791/7e81fa6c-5434-11e6-9d92-419d95951cd0.png">

**Comment by gr2m** [comment]
Hey @machikoyasuda do you want to try to fix it yourself?

The issue here is that we have `127.0.0.1` as the default bindAddress:
https://github.com/hoodiehq/hoodie/blob/master/cli/hoodie-defaults.js#L5

We don’t want to change it, the reason here is that we want to be secure by default. If you bind the server to `127.0.0.1` it means that it cannot be accessed in the same network from other computers. 

The problem though is that it shows `http://Machikos-MacBook-Pro.local:8080` while it should show `http://127.0.0.1:8080`. Hoodie is using [hapi](http://hapijs.com) for it’s server, and the console log that shows the url is here: https://github.com/hoodiehq/hoodie/blob/master/bin/start.js#L12, `server.info.uri` is what we want to change the value of.

We can do that by passing `options.host` to [server.connection([options])](http://hapijs.com/api#serverconnectionoptions). We already do that if the `url` option is set for the Hoodie app: https://github.com/hoodiehq/hoodie/blob/master/cli/hapi-options.js#L21-L23

So what we need to do is this (I think):
- if `options.url` is set, set `hapiOptions.connection.host` to `options.url`
- if it is not set, set `hapiOptions.connection.host` to `'http://127.0.0.1:' + options.port`

**Comment by machikoyasuda** [comment]
@gr2m Got it. I'll try it out this weekend. Thank you 🐶

**Comment by machikoyasuda** [comment]
Pairing on this with @kennethlee at @fullstackla today

**Comment by gr2m** [comment]
@machikoyasuda can I work on this with someone tonight at Fullstack LA? @jaimemendozadev maybe? Or @kennethlee? Or both? :D

**Comment by kennethlee** [comment]
@gr2m 👋 

I couldn't make it tonight, but maybe we can pair on this next time 😁

**Comment by gr2m** [comment]
sure if it’s still available :)

**Comment by nongaap** [comment]
I can take a crack at this too.

**Comment by gr2m** [comment]
good luck Mike :)

**Comment by nongaap** [comment]
@gr2m I think there are a few ways to fix this (although I'm not sure what the side effects would be)

A. To get `http://127.0.0.1:8080` we can refactor options.url in hapi-options.js to:

`if (options.url) {
    hapiOptions.connection.host = url.parse(options.url).hostname
  } else {
    hapiOptions.connection.host = '127.0.0.1'
  }`

But looking at the Hapi docs it states:

> host - the public hostname or IP address. Used only to set server.info.host and server.info.uri. If not configured, defaults to the operating system hostname and if not available, to 'localhost'.

B. Following how Hapi sets the host name we can set host name to 'localhost' in place of the operating system hostname:

`if (options.url) {
    hapiOptions.connection.host = url.parse(options.url).hostname
  } else {
    hapiOptions.connection.host = 'localhost'
  }`

Setting to 'localhost' would output: `http://localhost:8080/`

C. Alternatively, the start.js file can be refactored to replace `server.info.uri` with:

`console.log((process.platform === 'darwin' ? emoji.get('dog') + '  ' : '') + 'Your Hoodie app has started on:', server.info.protocol + '://' + server.info.address + ':' + server.info.port )`

This would output `http://127.0.0.1:8080` without changing hapi-options.js file.

Let me know if any of these approaches address the issue and I'd be happy to submit a PR.

**Comment by gr2m** [comment]
I’d suggest to go with B, I think localhost is more conventional than 127.0.0.1. We have the fast part of it implemented in https://github.com/hoodiehq/hoodie/blob/master/cli/hapi-options.js#L22-L24

**Comment by nongaap** [comment]
Thanks! Will make a PR in a bit.

**Comment by gr2m** [comment]
released as https://github.com/hoodiehq/hoodie/releases/tag/v24.2.3. Thanks so much! 

I’ve invited you to the Hoodie Contributors Teams, welcome 🐶🎉 
Are you on twitter? If like giving shout outs to new contributors 📯

**Comment by nongaap** [comment]
@gr2m woohoo! twitter handle is 'nongaap'

**Comment by gr2m** [comment]
done via #602
