### ISSUE TITLE
Progressive Render

### ISSUE THREAD

**Issue by NickColley** [hoodiehq/hoodie#560]
I've been thinking about this for a while but not got around to talking to anyone yet.

Has anyone thought about using the hoodie client on the server side? It'd be good to be able to progressively render an offline app, right now Hoodie is only setup for use on the clientside as far as I know?

**Comment by gr2m** [comment]
Yes a few people talked about it. We came to the conclusion that we need to make Hoodie entirely asynchronous which it’s not right now. And once it is, we would no longer use localStorage at all, but only PouchDB. And once we do that, running the Hoodie client in both server and Service Worker should be possible

Our current idea is to introduce a `hoodie.ready.then ...` Promise, so that we can keep the synchronous getters like `hoodie.account.username` and `hoodie.account.id`, they will be bootstrapped before `hoodie.ready` resolves

**Comment by NickColley** [comment]
Neat, thanks for the info. Will close out, hopefully can help out with that effort in the future.
