### ISSUE TITLE
Hoodie default page not showing

### ISSUE THREAD

**Issue by pmbanugo** [hoodiehq/hoodie#609]
I am running through the getting started guide and when I run the app without a public folder, I don't see the hoodie default page telling me that I need a `public` folder.

Also, when I navigate to any url e.g localhost:8080/home.html or any, it doesn't return a 404 or something.  Don't know if that's normal

**Comment by gr2m** [comment]
I had a quick look at it and found out that in [server/plugins/public.js](https://github.com/hoodiehq/hoodie/blob/1f9db057f25498db690883faaa6934c933b50f0a/server/plugins/public.js#L11) 

`options.config.public` is undefined, instead `options.config.paths.public` should be used. But `options.config.paths.public` is just `public` so it will still not work. We have to check if the `public/` folder exists in the current app and if not, default `options.config.paths.public` to `node_modules/hoodie/public`, it should probably happen in [cli/hoodie-defaults.js](https://github.com/hoodiehq/hoodie/blob/1f9db057f25498db690883faaa6934c933b50f0a/cli/hoodie-defaults.js)

**Comment by gr2m** [comment]
@benwhite-deltas let me know if you have any questions :) thanks for looking into it 👍

**Comment by minrwhite** [comment]
Pretty sure I've got a good idea of how I'm going to handle this:

hoodieDefaults.js module currently returns a function that returns a map of defaults, I'm planning to add another function as a property (of the function, not the map) that returns the absolute path to hoodie's 'public' dir.

In options.js I am planning to do the fs calls to determine the existence of the configured/default public directory, and otherwise fall back on the value returned from the function added above.

Alternatively the above function could accept a directory and return it back if it exists, or return hoodie's public dir if not. This would probably be easier to test and prevent having to add the fs dependency to options.js

Obviously, the object path to the public dir needs to be corrected and everything covered in lots of lovely testing.

Sound reasonable enough?
Deltas Software Ltd is a company registered in England &amp; Wales with registration number 08878020 at registered office Ordman House, 31 Arden Close, Bradley Stoke, Bristol, BS32 8AX. All rights reserved. No kittens were harmed in the sending of this email.

**Comment by gr2m** [comment]
I’m heads down with work, but please start a PR as soon as you start working on it for better discussion :) I think we should set `defaults.public` in `options.js` to `public` or to `node_modules/hoodie/public`, depending on weather the app has a `public` folder or not
