### ISSUE TITLE
localStorage limits

### ISSUE THREAD

**Issue by nevf** [hoodiehq/hoodie#61]
My overwhelming concern with frameworks/libraries like this that provide off-line support is the fundamental limits imposed by using localStorage, which varies between 2.5 and 10MB depending on the Browser. You then halve the number of bytes as strings are UTF-16 which uses 2 bytes per character. These limits are way too small for anything but the simplest of applications. Unfortunately [there is no simple solution for local storage](https://hacks.mozilla.org/2012/03/there-is-no-simple-solution-for-local-storage/)

**Comment by gr2m** [comment]
nevf, thanks for your feedback. 

I agree that especially localStorage is not the best technology. We decided for it because of it's simplicity, not capacity. But when you look at `hoodie.store`, it's just an abstract API, hiding away the actual persistance layer. So what you could do for example is take something like IndexedDB or what ever will be the best solution tomorrow, and write the hoodie.store adapter on top of it. As long as the developer facing API does not change, nobody cares, really.

There could even exist multiple implementations among each other, for example you could build an implementation on top of IndexDB for modern / mobile browsers, while we keep the localStorage implementation for use cases where compatibility or code simplicity is more important than capacity and performance.

Does that make sense? You're more than invited to build a better hoodie.store implementation, I'm happy to support you with that

**Comment by gr2m** [comment]
and btw, 5MB is available across todays browsers as far as I know. And as long as you don't work with binaries like images, that's a shit load of data you can store. I use it for example at minutes.io and since 2 years, there was not a single case where someone would have more than 2MB of data. It's just text after all, even when you count 2 bytes, per character, that's 2,621,440 characters in total. 

At some point, it will make sense not to download all users data, instead use it as a subset of data the user is currently working on. But that's a whole different story.

**Comment by caolan** [comment]
I have this problem on another project, where I'm storing slightly too much for localstorage in some cases. However, localstorage is much faster to load from than indexeddb on page load. Think I might put together a very simple localstorage-like api (but async) that will switch to indexeddb if the quota is exceeded. That could make a good storage layer for Hoodie, at least until we get into operating on subsets of user data.

**Comment by gr2m** [comment]
our hoodie.store API is async already ;-) All set for some @caolan magic behind the curtain

**Comment by caolan** [comment]
@nevf agreed, the technology isn't great at the moment, but it is workable, and this is my bread and butter so it'll get sorted :)

**Comment by nevf** [comment]
@gr2m @caolan Good to hear that the store is a thin abstract layer that can use other back-ends. For an App I'm developing which uses MongoDB and Node.js on the server, database size can easily get into the 100's of MBs and GB's. In order  to work off-line localStorage is useless, even just with a subset of the data. And a simple key-value store would be painful to code for and unlikely to be performant. Unfortunately database use in the browser is a mess with no obvious sign this will improve any time soon, making it very difficult to cater for serious off-line apps with larger data and more complex model requirements.

**Comment by janl** [comment]
pouchdb.com is the obvious sign of improvement in this space :)

Although, like for us, selective sync is still on the roadmap, but rest assured we’ll get there. For now, we focus on getting the limited use-cases to work properly and then expand.

**Comment by nevf** [comment]
@janl I am well aware of pouchdb but haven't looked at it in a while. Does it use WebSQL on mobile devices and IndexedDB on Desktop browsers? 

I spent some time evaluating CouchDB for this App but it didn't fit my use case, which was ideally handled by MongoDB. That said the off-line and sync capabilities of CouchDB are awesome.

**Comment by janl** [comment]
On 15.05.2013, at 13:49, Neville Franks notifications@github.com wrote:

> @janl I am well aware of pouchdb but haven't looked at it in a while. Does it use WebSQL on mobile devices and IndexedDB on Desktop browsers?
> 
> Yup.
> I spent some time evaluating CouchDB for this App but it didn't fit my use case, which was ideally handled by MongoDB. That said the off-line and sync capabilities of CouchDB are awesome.
> 
> Sure thing, didn't meant to make this a plug for either one, just reporting on progress in the field :)

Always use tech that solves your problem :)
