### ISSUE TITLE
docs: hoodie client API

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#698]
Currently our Hoodie client API is pretty empty
http://docs.hood.ie/en/latest/api/client/hoodie.html

The README of [hoodie-client](https://github.com/hoodiehq/hoodie-client) is complete though, so all we need to do is to copy the API docs over and adapt the syntax from Markdown to Restructured Text (.md to .rst)

@NimmiW is looking into it

**Comment by NimmiW** [comment]
[solved this error] @fozy81 I am currently trying to setup the documentation locally as mentioned in the following link. 

https://github.com/hoodiehq/hoodie/blob/master/docs/developers/CONTRIBUTING_DOCS.rst#make-big-changes

I am a Windows user. 

My commands were as follows.
```
C:\Users\Nimmi\Documents\Hoodie\hoodie>pip install sphinx
C:\Users\Nimmi\Documents\Hoodie\hoodie>pip install sphinx_rtd_theme
C:\Users\Nimmi\Documents\Hoodie\hoodie>cd docs
C:\Users\Nimmi\Documents\Hoodie\hoodie\docs>make html
```

The issue is that 'make html' command is giving me errors.

The Error is as follows: 

```
make : The term 'make' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ make html
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Since I was using powershell in windows, the 'make' had to be installed. So I installed it from the link below.

http://gnuwin32.sourceforge.net/packages/make.htm

Now make is recognized by the powershell. but the problem is it is giving me the following error

```
C:\Users\Nimmi\Documents\Hoodie\hoodie\docs>make html
make: *** No rule to make target `html'.  Stop.
```

I found my silly mistake. I was working with my old repo. I had to re pull after gregor did the last merge, :)

Now I am way back to edit the documentation.

**Comment by fozy81** [comment]
Ahh, great! :smile: sounds like you got it working, and good to know it works fine on windows, maybe worth adding a note for powershell users into [contributing docs](https://github.com/hoodiehq/hoodie/blob/master/docs/developers/CONTRIBUTING_DOCS.rst) if installing 'make' needs a mention. 
  
Look forward to see how you get on with updating API docs. I'm new to .rst format and travis testing docs but got inspired by [writethedocs.org](http://www.writethedocs.org/guide/) - go scratch the itch!

**Comment by gr2m** [comment]
> I found my silly mistake

Not silly at all! Glad you figured it out!

> maybe worth adding a note for powershell users into contributing docs

I think mentioning how to get `make` on Windows working would be a great a great addition to our docs :)

**Comment by NimmiW** [comment]
@gr2m and @fozy81 I will add a note for poweshell users to the contributing docs :) 

![image](https://cloud.githubusercontent.com/assets/26009680/23342543/c2a3e042-fc82-11e6-9a2c-54a3a4e6c933.png)

Is this note is ok? I added hyperlinks for downloading 'make'

**Comment by gr2m** [comment]
@NimmiW I wold suggest you start a pull request for it? Then we can discuss there, it’s easier for use to make suggestions because we can comment directly below lines that you changed

**Comment by pmbanugo** [comment]
[MSYS2](http://www.msys2.org) is also an option. I haven't used it but saw [this on Stackoverflow](http://stackoverflow.com/a/40102007). I've used CygWin and ConEmu just to run some linux commands on Windows and they seem to play well. 

MSYS2 seems to be a better choice for linux command on windows. See [Difference between MSYS2 and CygWin](http://stackoverflow.com/a/25755481)

I saw this [answer](http://stackoverflow.com/a/40102007) on Stackoverflow so maybe we could consider adding MSYS2 option as a way to get that working on windows?

**Comment by NimmiW** [comment]
@gr2m I created my first pull request and it was merged by jan :) currently I am working on the api client documentation

**Comment by NimmiW** [comment]
@pmbanugo I will go through the thing you mentioned and try to integrate that knowledge also.

**Comment by NimmiW** [comment]
hi all @gr2m @fozy81 @pmbanugo @Litarhis @badboy 

```
C:\Users\Nimmi\Documents\Hoodie\hoodie\docs>make html
make: *** No rule to make target `html'.  Stop.
```

I again getting this error now.

I would be gratefull if someone can give me a clue where I am heading. 

This command executed successfully yesterday. But now it is not working.

**Comment by fozy81** [comment]
@NimmiW Sorry, the `make html` isn't working. I removed the makefile and conf.py from the docs/ folder because it was stopping the documents from building on [readthedocs]( http://readthedocs.org/projects/hoodie/builds/5075127/) . See discussion here https://github.com/hoodiehq/hoodie/pull/694. 

For the moment, if you type `sphinx-quickstart` this will walk you through setting up Makefile and confy.py and build the docs locally more info [here](http://docs.readthedocs.io/en/latest/getting_started.html).

I've hope to add the Makefile and conf.py back into the hoodie/docs so `make html` will work as it should.  :smile:

**Comment by NimmiW** [comment]
@fozy81 Thank you for the information :)

**Comment by NimmiW** [comment]
@fozy81 
`# PROTIP™ Pipe output through a [pretty reporter](https://www.npmjs.com/package/tape#pretty-reporters)`

What does this actually means?

**Comment by fozy81** [comment]
Hi @NimmiW, I'm not sure. Maybe @gr2m can explain more?

**Comment by gr2m** [comment]
@NimmiW you can ignore that part.

What it means is that tape by itself returns output in the [TAP format](https://testanything.org/) and recommends to use "pretty reporters" for nice formatting. [tap-spec](https://github.com/scottcorgan/tap-spec) or [tap-min](https://github.com/gummesson/tap-min) are such formatters. "Piping" means to use the "|" pipe sign, e.g.

```
tape test/*.js | tap-spec
tape test/*.js | tap-min
```

**Comment by gr2m** [comment]
this is done: http://docs.hood.ie/en/latest/api/client/hoodie.html 👏
